### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [CodaFi/LOLCODE.tmLanguage#2]
I would like to use your grammar for LOLCODE but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by CodaFi** [comment]
Thanks you so much for bringing this up.  I would hate for people to not use this because of licensing issues.  It's under MIT now (see a8088630cf3c174f82261eac1eb827dfb0688db2).

**Comment by pchaigno** [comment]
Thanks!
